### ISSUE TITLE
about

### ISSUE THREAD

**Issue by 9313135** [mrepol742/IndexNow#1]
static String format = "https://bing.com/indexnow?url=https://mrepol742.github.io%1$s&key=f20756182df645f9b8cf6254654dd5da"
%1$s  What does this mean, please? In learning, I can't understand what this code means.

**Comment by mrepol742** [comment]
Hi [9313135](https://github.com/9313135),

the %1$s is the path to the page for example https://mrepol742.github.io/webvium/ or https://mrepol742.github.io/webviumdev/ the path are stored in arrays of Strings. 
``` Java
static String[] sg = new String[]{};
```
You can get your own key at [https://www.bing.com/indexnow](https://www.bing.com/indexnow).

The live demo of this program was in [https://github.com/mrepol742/mrepol742.github.io/actions/workflows/index.yml](https://github.com/mrepol742/mrepol742.github.io/actions/workflows/index.yml).

**Comment by 9313135** [comment]
thank you
